### ISSUE TITLE
Create a signup page

### ISSUE THREAD

**Issue by minndoo** [varwishteam/varwish-fe#2]
Create a form that will have no functionality atm.
Acceptance criteria:
* Create a form according to the design
* Just dummy form, no functionality

**Comment by minndoo** [comment]
Shouldn't include any links to the features in application. (link to user's account, link to wishlist management, etc.) 
Overall should include a layout that looks nice and has no functionality

**Comment by tomastrejdl** [comment]
I already created a basic login page, so I'm changing this to signup.
